### PR TITLE
Allow docs-only parameter when building

### LINKED ISSUE #91: Allow --docs flag in build script
Storybook accepts a `--docs` flag in its native build script to build only the `docs` views and not the canvas. It would be great that this plugin allow to pass this flag and forward it to Storybook.

Reference: https://github.com/storybookjs/storybook/blob/d1196f73767caaa724a6984ef7409748e0329075/lib/core/src/server/cli/prod.js#L23

### PR DESCRIPTION
**Pull request by LeBenLeBen**
Fix #91

### CODE REVIEW

**Comment by LeBenLeBen** [comment]
@pksunkara do you have any plan to push a release including this feature sometime soon?

**Comment by pksunkara** [comment]
I will do it tonight.

**Comment by pksunkara** [comment]
Done.

**Comment by LeBenLeBen** [comment]
Thank you!

**Pull request merged**
